name: sustain
services:
  database:
    container_name: sustain_database
    image: bitnami/postgresql
    volumes:
      - database_data:/bitnami/postgresql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_DATABASE=main
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=${MASTER_KEY}
    ports:
      - 5432:5432
volumes:
  database_data:
